# Generated by Django 2.2.6 on 2019-10-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.PositiveSmallIntegerField(default=18207),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='coupon_code',
            field=models.PositiveSmallIntegerField(default=24987),
        ),
    ]
